// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: k8stty.proto

package k8stty

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ingresses
type CreateIngressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IngressId string `protobuf:"bytes,1,opt,name=ingressId,proto3" json:"ingressId,omitempty"`
}

func (x *CreateIngressReq) Reset() {
	*x = CreateIngressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIngressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngressReq) ProtoMessage() {}

func (x *CreateIngressReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngressReq.ProtoReflect.Descriptor instead.
func (*CreateIngressReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIngressReq) GetIngressId() string {
	if x != nil {
		return x.IngressId
	}
	return ""
}

type CreateIngressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateIngressResp) Reset() {
	*x = CreateIngressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIngressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngressResp) ProtoMessage() {}

func (x *CreateIngressResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngressResp.ProtoReflect.Descriptor instead.
func (*CreateIngressResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIngressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteIngressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IngressId string `protobuf:"bytes,1,opt,name=ingressId,proto3" json:"ingressId,omitempty"`
}

func (x *DeleteIngressReq) Reset() {
	*x = DeleteIngressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIngressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngressReq) ProtoMessage() {}

func (x *DeleteIngressReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngressReq.ProtoReflect.Descriptor instead.
func (*DeleteIngressReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteIngressReq) GetIngressId() string {
	if x != nil {
		return x.IngressId
	}
	return ""
}

type DeleteIngressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteIngressResp) Reset() {
	*x = DeleteIngressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIngressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngressResp) ProtoMessage() {}

func (x *DeleteIngressResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngressResp.ProtoReflect.Descriptor instead.
func (*DeleteIngressResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteIngressResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// namespaces
type CreateNamespaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamespaceId string `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
}

func (x *CreateNamespaceReq) Reset() {
	*x = CreateNamespaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNamespaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceReq) ProtoMessage() {}

func (x *CreateNamespaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceReq.ProtoReflect.Descriptor instead.
func (*CreateNamespaceReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNamespaceReq) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type CreateNamespaceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateNamespaceResp) Reset() {
	*x = CreateNamespaceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNamespaceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResp) ProtoMessage() {}

func (x *CreateNamespaceResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResp.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNamespaceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteNamespaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NamespaceId string `protobuf:"bytes,1,opt,name=namespaceId,proto3" json:"namespaceId,omitempty"`
}

func (x *DeleteNamespaceReq) Reset() {
	*x = DeleteNamespaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNamespaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceReq) ProtoMessage() {}

func (x *DeleteNamespaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceReq.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNamespaceReq) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

type DeleteNamespaceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteNamespaceResp) Reset() {
	*x = DeleteNamespaceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNamespaceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResp) ProtoMessage() {}

func (x *DeleteNamespaceResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResp.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNamespaceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// networkpolicies
type CreateNetworkpolicyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkpolicyId string `protobuf:"bytes,1,opt,name=networkpolicyId,proto3" json:"networkpolicyId,omitempty"`
}

func (x *CreateNetworkpolicyReq) Reset() {
	*x = CreateNetworkpolicyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNetworkpolicyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkpolicyReq) ProtoMessage() {}

func (x *CreateNetworkpolicyReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkpolicyReq.ProtoReflect.Descriptor instead.
func (*CreateNetworkpolicyReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNetworkpolicyReq) GetNetworkpolicyId() string {
	if x != nil {
		return x.NetworkpolicyId
	}
	return ""
}

type CreateNetworkpolicyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateNetworkpolicyResp) Reset() {
	*x = CreateNetworkpolicyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNetworkpolicyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkpolicyResp) ProtoMessage() {}

func (x *CreateNetworkpolicyResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkpolicyResp.ProtoReflect.Descriptor instead.
func (*CreateNetworkpolicyResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNetworkpolicyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteNetworkpolicyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkpolicyId string `protobuf:"bytes,1,opt,name=networkpolicyId,proto3" json:"networkpolicyId,omitempty"`
}

func (x *DeleteNetworkpolicyReq) Reset() {
	*x = DeleteNetworkpolicyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNetworkpolicyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkpolicyReq) ProtoMessage() {}

func (x *DeleteNetworkpolicyReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkpolicyReq.ProtoReflect.Descriptor instead.
func (*DeleteNetworkpolicyReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNetworkpolicyReq) GetNetworkpolicyId() string {
	if x != nil {
		return x.NetworkpolicyId
	}
	return ""
}

type DeleteNetworkpolicyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteNetworkpolicyResp) Reset() {
	*x = DeleteNetworkpolicyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNetworkpolicyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkpolicyResp) ProtoMessage() {}

func (x *DeleteNetworkpolicyResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkpolicyResp.ProtoReflect.Descriptor instead.
func (*DeleteNetworkpolicyResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNetworkpolicyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// pods
type CreatePodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodId     string `protobuf:"bytes,1,opt,name=podId,proto3" json:"podId,omitempty"`
	ImageName string `protobuf:"bytes,2,opt,name=imageName,proto3" json:"imageName,omitempty"`
}

func (x *CreatePodReq) Reset() {
	*x = CreatePodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodReq) ProtoMessage() {}

func (x *CreatePodReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodReq.ProtoReflect.Descriptor instead.
func (*CreatePodReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePodReq) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *CreatePodReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type CreatePodResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreatePodResp) Reset() {
	*x = CreatePodResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodResp) ProtoMessage() {}

func (x *CreatePodResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodResp.ProtoReflect.Descriptor instead.
func (*CreatePodResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePodResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodId string `protobuf:"bytes,1,opt,name=podId,proto3" json:"podId,omitempty"`
}

func (x *DeletePodReq) Reset() {
	*x = DeletePodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodReq) ProtoMessage() {}

func (x *DeletePodReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodReq.ProtoReflect.Descriptor instead.
func (*DeletePodReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePodReq) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

type DeletePodResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeletePodResp) Reset() {
	*x = DeletePodResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodResp) ProtoMessage() {}

func (x *DeletePodResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodResp.ProtoReflect.Descriptor instead.
func (*DeletePodResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{15}
}

func (x *DeletePodResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// services
type CreateServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
}

func (x *CreateServiceReq) Reset() {
	*x = CreateServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceReq) ProtoMessage() {}

func (x *CreateServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceReq.ProtoReflect.Descriptor instead.
func (*CreateServiceReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{16}
}

func (x *CreateServiceReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type CreateServiceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateServiceResp) Reset() {
	*x = CreateServiceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceResp) ProtoMessage() {}

func (x *CreateServiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceResp.ProtoReflect.Descriptor instead.
func (*CreateServiceResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{17}
}

func (x *CreateServiceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
}

func (x *DeleteServiceReq) Reset() {
	*x = DeleteServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceReq) ProtoMessage() {}

func (x *DeleteServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceReq.ProtoReflect.Descriptor instead.
func (*DeleteServiceReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteServiceReq) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeleteServiceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteServiceResp) Reset() {
	*x = DeleteServiceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServiceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResp) ProtoMessage() {}

func (x *DeleteServiceResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResp.ProtoReflect.Descriptor instead.
func (*DeleteServiceResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteServiceResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// check origin
type CheckOriginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *CheckOriginReq) Reset() {
	*x = CheckOriginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOriginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOriginReq) ProtoMessage() {}

func (x *CheckOriginReq) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOriginReq.ProtoReflect.Descriptor instead.
func (*CheckOriginReq) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{20}
}

func (x *CheckOriginReq) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type CheckOriginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CheckOriginResp) Reset() {
	*x = CheckOriginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_k8stty_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOriginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOriginResp) ProtoMessage() {}

func (x *CheckOriginResp) ProtoReflect() protoreflect.Message {
	mi := &file_k8stty_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOriginResp.ProtoReflect.Descriptor instead.
func (*CheckOriginResp) Descriptor() ([]byte, []int) {
	return file_k8stty_proto_rawDescGZIP(), []int{21}
}

func (x *CheckOriginResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_k8stty_proto protoreflect.FileDescriptor

var file_k8stty_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x22, 0x30, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x22, 0x2f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x36, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0x33,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a,
	0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x29, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x6f, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49,
	0x64, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x2d,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x30, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x28,
	0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x99, 0x01, 0x0a, 0x07, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6b,
	0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x2e, 0x6b, 0x38, 0x73,
	0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x32, 0xa7, 0x01, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x4c, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x1a, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4c, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x1a, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6b,
	0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0xc3, 0x01, 0x0a, 0x0d,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x58, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x1e, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1e,
	0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1f,
	0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x32, 0x7d, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x3a, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x14, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6b, 0x38,
	0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x64, 0x12, 0x14, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x32, 0x99, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e,
	0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x49, 0x0a, 0x0b,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x05, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6b,
	0x38, 0x73, 0x74, 0x74, 0x79, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x6b, 0x38, 0x73, 0x74, 0x74,
	0x79, 0x2f, 0x6b, 0x38, 0x73, 0x74, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_k8stty_proto_rawDescOnce sync.Once
	file_k8stty_proto_rawDescData = file_k8stty_proto_rawDesc
)

func file_k8stty_proto_rawDescGZIP() []byte {
	file_k8stty_proto_rawDescOnce.Do(func() {
		file_k8stty_proto_rawDescData = protoimpl.X.CompressGZIP(file_k8stty_proto_rawDescData)
	})
	return file_k8stty_proto_rawDescData
}

var file_k8stty_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_k8stty_proto_goTypes = []interface{}{
	(*CreateIngressReq)(nil),        // 0: k8stty.CreateIngressReq
	(*CreateIngressResp)(nil),       // 1: k8stty.CreateIngressResp
	(*DeleteIngressReq)(nil),        // 2: k8stty.DeleteIngressReq
	(*DeleteIngressResp)(nil),       // 3: k8stty.DeleteIngressResp
	(*CreateNamespaceReq)(nil),      // 4: k8stty.CreateNamespaceReq
	(*CreateNamespaceResp)(nil),     // 5: k8stty.CreateNamespaceResp
	(*DeleteNamespaceReq)(nil),      // 6: k8stty.DeleteNamespaceReq
	(*DeleteNamespaceResp)(nil),     // 7: k8stty.DeleteNamespaceResp
	(*CreateNetworkpolicyReq)(nil),  // 8: k8stty.CreateNetworkpolicyReq
	(*CreateNetworkpolicyResp)(nil), // 9: k8stty.CreateNetworkpolicyResp
	(*DeleteNetworkpolicyReq)(nil),  // 10: k8stty.DeleteNetworkpolicyReq
	(*DeleteNetworkpolicyResp)(nil), // 11: k8stty.DeleteNetworkpolicyResp
	(*CreatePodReq)(nil),            // 12: k8stty.CreatePodReq
	(*CreatePodResp)(nil),           // 13: k8stty.CreatePodResp
	(*DeletePodReq)(nil),            // 14: k8stty.DeletePodReq
	(*DeletePodResp)(nil),           // 15: k8stty.DeletePodResp
	(*CreateServiceReq)(nil),        // 16: k8stty.CreateServiceReq
	(*CreateServiceResp)(nil),       // 17: k8stty.CreateServiceResp
	(*DeleteServiceReq)(nil),        // 18: k8stty.DeleteServiceReq
	(*DeleteServiceResp)(nil),       // 19: k8stty.DeleteServiceResp
	(*CheckOriginReq)(nil),          // 20: k8stty.CheckOriginReq
	(*CheckOriginResp)(nil),         // 21: k8stty.CheckOriginResp
}
var file_k8stty_proto_depIdxs = []int32{
	0,  // 0: k8stty.Ingress.CreateIngress:input_type -> k8stty.CreateIngressReq
	2,  // 1: k8stty.Ingress.DeleteIngress:input_type -> k8stty.DeleteIngressReq
	4,  // 2: k8stty.Namespace.CreateNamespace:input_type -> k8stty.CreateNamespaceReq
	6,  // 3: k8stty.Namespace.DeleteNamespace:input_type -> k8stty.DeleteNamespaceReq
	8,  // 4: k8stty.Networkpolicy.CreateNetworkpolicy:input_type -> k8stty.CreateNetworkpolicyReq
	10, // 5: k8stty.Networkpolicy.DeleteNetworkpolicy:input_type -> k8stty.DeleteNetworkpolicyReq
	12, // 6: k8stty.Pod.CreatePod:input_type -> k8stty.CreatePodReq
	14, // 7: k8stty.Pod.DeletePod:input_type -> k8stty.DeletePodReq
	16, // 8: k8stty.Service.CreateService:input_type -> k8stty.CreateServiceReq
	18, // 9: k8stty.Service.DeleteService:input_type -> k8stty.DeleteServiceReq
	20, // 10: k8stty.CheckOrigin.Check:input_type -> k8stty.CheckOriginReq
	1,  // 11: k8stty.Ingress.CreateIngress:output_type -> k8stty.CreateIngressResp
	3,  // 12: k8stty.Ingress.DeleteIngress:output_type -> k8stty.DeleteIngressResp
	5,  // 13: k8stty.Namespace.CreateNamespace:output_type -> k8stty.CreateNamespaceResp
	7,  // 14: k8stty.Namespace.DeleteNamespace:output_type -> k8stty.DeleteNamespaceResp
	9,  // 15: k8stty.Networkpolicy.CreateNetworkpolicy:output_type -> k8stty.CreateNetworkpolicyResp
	11, // 16: k8stty.Networkpolicy.DeleteNetworkpolicy:output_type -> k8stty.DeleteNetworkpolicyResp
	13, // 17: k8stty.Pod.CreatePod:output_type -> k8stty.CreatePodResp
	15, // 18: k8stty.Pod.DeletePod:output_type -> k8stty.DeletePodResp
	17, // 19: k8stty.Service.CreateService:output_type -> k8stty.CreateServiceResp
	19, // 20: k8stty.Service.DeleteService:output_type -> k8stty.DeleteServiceResp
	21, // 21: k8stty.CheckOrigin.Check:output_type -> k8stty.CheckOriginResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_k8stty_proto_init() }
func file_k8stty_proto_init() {
	if File_k8stty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_k8stty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIngressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIngressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIngressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIngressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNamespaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNamespaceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNamespaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNamespaceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNetworkpolicyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNetworkpolicyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNetworkpolicyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNetworkpolicyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePodResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePodResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServiceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServiceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOriginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_k8stty_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOriginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_k8stty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_k8stty_proto_goTypes,
		DependencyIndexes: file_k8stty_proto_depIdxs,
		MessageInfos:      file_k8stty_proto_msgTypes,
	}.Build()
	File_k8stty_proto = out.File
	file_k8stty_proto_rawDesc = nil
	file_k8stty_proto_goTypes = nil
	file_k8stty_proto_depIdxs = nil
}
