---
version: '3'
services:
  nginx:
    image: nginx:latest
    networks:
      - k8stty
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
  terminal-svc:
    image: localhost:5001/terminal:latest
    networks:
      - k8stty
    ports:
      - "9000:9000"
    env_file:
      - ./.env
  websocket-svc:
    image: localhost:5001/websocket:latest
    networks:
      - k8stty
    ports:
      - "9001:9001"
    env_file:
      - ./.env
    volumes:
      - ~/.kube/config:/home/server/.kube/config
  namespace-svc:
    image: localhost:5001/namespace:latest
    networks:
      - k8stty
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    volumes:
      - ~/.kube/config:/home/server/.kube/config
  networkpolicy-svc:
    image: localhost:5001/networkpolicy:latest
    networks:
      - k8stty
    ports:
      - "8082:8082"
    env_file:
      - ./.env
    volumes:
      - ~/.kube/config:/home/server/.kube/config
  pod-svc:
    image: localhost:5001/pod:latest
    networks:
      - k8stty
    ports:
      - "8083:8083"
    env_file:
      - ./.env
    volumes:
      - ~/.kube/config:/home/server/.kube/config
  service-svc:
    image: localhost:5001/service:latest
    networks:
      - k8stty
    ports:
      - "8084:8084"
    env_file:
      - ./.env
    volumes:
      - ~/.kube/config:/home/server/.kube/config

networks:
  k8stty:
