apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/services.yaml
  - resources/deployments.yaml
  - resources/configs.yaml
  - resources/clusterroles.yaml
  - resources/clusterrolebindings.yaml
