---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8stty
  name: registry-url
data:
  url: https://index.docker.io/v1/k8stty/

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8stty
  name: allowed-images
data:
  images: |
    alpine:3
    busybox:stable
    busybox:stable-musl
    debian:bookworm
    debian:bookworm-slim
    python:bookworm
    python:bullseye
    ubuntu:focal
    ubuntu:jammy

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8stty
  name: allowed-origins
data:
  origins: |
    http://127.0.0.1:8080
    http://localhost:8080

